### ISSUE TITLE
Actividad 2 infografia 

### ISSUE THREAD

**Issue by alex13-loca** [SistemasTecTlaxiaco/actividad-2-infografia-alex13-loca#1]
![9DF3BAF7-80DB-4B87-9A11-B80754D1A57A](https://user-images.githubusercontent.com/112469592/187779798-c82d59ab-7e9f-45d7-8bdf-856a6f914bcb.jpeg)

Actividad 2 
Alexis Hernández Cruz 
1BS

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 2 INFOGRAFIA
DE 20% DE LA ACTIVIDAD OBTUVISTE 14.8 % DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
